const state = { base: localStorage.getItem('API_BASE_URL') || 'http://127.0.0.1:8000' }
const $ = s => document.querySelector(s)
const $$ = s => [...document.querySelectorAll(s)]
$('#apiBase').value = state.base
$('#saveApi').onclick = () => { state.base = $('#apiBase').value.trim(); localStorage.setItem('API_BASE_URL', state.base); alert('已保存后端地址') }
$$('.nav').forEach(btn => btn.onclick = () => switchView(btn.dataset.view))
$$('[data-jump]').forEach(btn => btn.onclick = () => switchView(btn.dataset.jump))
function switchView(id){ $$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===id)); $$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id)); if(id==='progress') loadProgress() }
async function api(path, opt={}){ const token=localStorage.getItem('token')||localStorage.getItem('access_token')||''; const res=await fetch(state.base+path,{method:opt.method||'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:opt.data?JSON.stringify(opt.data):undefined}); if(!res.ok) throw await res.json().catch(()=>({detail:res.statusText})); return res.json() }
function mock(){ return { profile:{ tag_preferences:[{name:'人工智能',weight:.94},{name:'Python',weight:.82},{name:'科幻',weight:.68},{name:'历史',weight:.52},{name:'算法',weight:.76}], high_rating_books:[{title:'深度学习入门',rating:5},{title:'三体',rating:4.8},{title:'机器学习',rating:4.7}] }, stats:{ total_reading_minutes:1260, finished_books:9, rating_count:14, bookmark_count:23 }, progress:[{book_title:'深度学习入门',progress_percent:72,current_page:186},{book_title:'三体',progress_percent:48,current_page:152},{book_title:'人类简史',progress_percent:89,current_page:341}] } }
async function refresh(){ let data; try{ const [profile,stats,progress]=await Promise.all([api('/api/v1/user/profile'),api('/api/v1/user/stats'),api('/api/v1/user/progress')]); data={profile,stats,progress:Array.isArray(progress)?progress:(progress.items||[])} }catch(e){ data=mock() } render(data) }
function render({profile,stats,progress}){ $('#mMinutes').textContent=stats.total_reading_minutes||0; $('#mFinished').textContent=stats.finished_books||0; $('#mRatings').textContent=stats.rating_count||0; $('#mBookmarks').textContent=stats.bookmark_count||0; $('#tags').innerHTML=(profile.tag_preferences||[]).map(t=>`<span class="tag" style="font-size:${14+(t.weight||.5)*10}px">${t.name||t.tag} · ${Math.round((t.weight||.5)*100)}%</span>`).join('')||'<span class="tag">暂无画像标签</span>'; $('#books').innerHTML=(profile.high_rating_books||profile.high_rated_books||[]).map(b=>`<div class="book"><div class="cover">${(b.title||'书').slice(0,1)}</div><div><b>${b.title||b.book_title}</b><p>评分 ${b.rating||b.score||'—'}</p></div></div>`).join('')||'<p>暂无高分图书</p>'; renderProgress(progress) }
function renderProgress(list=[]){ $('#progressList').innerHTML=(list||mock().progress).map(i=>`<div class="progress-item"><div class="progress-top"><span>${i.book_title||i.title||'未知图书'}</span><span>${i.progress_percent||0}%</span></div><div class="bar"><div style="width:${i.progress_percent||0}%"></div></div><small>当前第 ${i.current_page||0} 页</small></div>`).join('') }
async function loadProgress(){ try{ const res=await api('/api/v1/user/progress'); renderProgress(Array.isArray(res)?res:(res.items||[])) }catch(e){ renderProgress(mock().progress) } }
$('#refresh').onclick=refresh
function addMsg(text, role='assistant'){ const d=document.createElement('div'); d.className='msg '+role; d.textContent=text; $('#chatList').appendChild(d); $('#chatList').scrollTop=999999 }
async function sendChat(text){ const msg=text||$('#chatInput').value.trim(); if(!msg)return; $('#chatInput').value=''; addMsg(msg,'user'); try{ const res=await api('/api/v1/chat/send',{method:'POST',data:{message:msg,conversation_id:0}}); addMsg(res.content||res.answer||'已收到') }catch(e){ addMsg('智能助手接口暂不可用。请确认后端已启动，个人阅读问答需要先登录。') } }
$('#sendChat').onclick=()=>sendChat(); $('#chatInput').onkeydown=e=>{if(e.key==='Enter')sendChat()}; $$('.quick button').forEach(b=>b.onclick=()=>sendChat(b.textContent)); refresh()
