CREATE CONSTRAINT book_id IF NOT EXISTS FOR (b:Book) REQUIRE b.id IS UNIQUE;
CREATE CONSTRAINT author_id IF NOT EXISTS FOR (a:Author) REQUIRE a.id IS UNIQUE;
CREATE CONSTRAINT tag_id IF NOT EXISTS FOR (t:Tag) REQUIRE t.id IS UNIQUE;
CREATE CONSTRAINT publisher_id IF NOT EXISTS FOR (p:Publisher) REQUIRE p.id IS UNIQUE;
CREATE CONSTRAINT series_id IF NOT EXISTS FOR (s:Series) REQUIRE s.id IS UNIQUE;
CREATE INDEX book_title IF NOT EXISTS FOR (b:Book) ON (b.title);
CREATE INDEX tag_name IF NOT EXISTS FOR (t:Tag) ON (t.name);
MERGE (b:Book {id:1}) SET b.title='三体', b.category='科幻';
MERGE (a:Author {id:1}) SET a.name='刘慈欣';
MERGE (t:Tag {id:1}) SET t.name='科幻';
MERGE (p:Publisher {id:1}) SET p.name='重庆出版社';
MERGE (s:Series {id:1}) SET s.name='三体系列';
MATCH (b:Book {id:1}),(a:Author {id:1}) MERGE (b)-[:AUTHORED_BY]->(a);
MATCH (b:Book {id:1}),(t:Tag {id:1}) MERGE (b)-[:TAGGED_AS]->(t);
MATCH (b:Book {id:1}),(p:Publisher {id:1}) MERGE (b)-[:PUBLISHED_BY]->(p);
MATCH (b:Book {id:1}),(s:Series {id:1}) MERGE (b)-[:BELONGS_TO_SERIES]->(s);
